services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../frontend:/app/frontend
      - .:/app/backend
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2G