services:
  api:
    build:
      context: .  # Changed from .. to .
      dockerfile: Dockerfile  # Changed since we're in backend directory
    ports:
      - "8000:8000"
    volumes:
      - .:/app/backend
      - ../frontend:/app/frontend  # This is fine for frontend files
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2G